### ISSUE TITLE
What's the training data format?

### ISSUE THREAD

**Issue by yingnan-rl** [Mrgemy95/Recurrent-Environment-Simulators#1]
thanks for your code,it helps a lot.But what is the data format?For example,the states.npy.
The reinforcement learning sample is a tuple like <s,a,s',r>, given <s,a,s',r>. How to build states.npy, action.npy and reward.npy?

**Comment by mgsalem** [comment]
states format :  [data size]+[state shape]
action format : [data size ,1]
reward format : [data size ,1]
